import Header from "@/components/almaprep/Header"
import Footer from "@/components/almaprep/Footer"
import RevealOnScroll from "@/components/almaprep/RevealOnScroll"
import { pageMetadata } from "@/lib/seo"

export const metadata = pageMetadata({
  title: "Privacy Policy",
  description:
    "How Almaprep collects, uses, and protects your data — including student and children's data for institutions. We never sell student data.",
  path: "/privacy",
})

export default function PrivacyPage() {
  return (
    <div className="almaprep-theme">
      <RevealOnScroll />
      <Header />

      <main>
        <section className="section">
          <div className="wrap prose">
            <h1>Privacy Policy</h1>
            <p style={{ color: "var(--muted)" }}>Last updated: 7 June 2026</p>
            <p><em>This is a placeholder policy for the marketing site. Replace it with your finalized, legally reviewed policy before launch.</em></p>

            <h2>Who we are</h2>
            <p>Almaprep (&ldquo;we&rdquo;, &ldquo;us&rdquo;) provides an interview-practice platform for students and institutions. This policy explains what we collect and how we use it.</p>

            <h2>What we collect</h2>
            <ul>
              <li><strong>Account information</strong> such as name and email.</li>
              <li><strong>Practice data</strong> such as your answers, scores, resume text you upload, and session history.</li>
              <li><strong>Camera and microphone data during a practice interview</strong>, if you grant permission. See &ldquo;Camera and microphone&rdquo; below for exactly what happens to it.</li>
              <li><strong>Usage data</strong> such as device information and analytics — only if you accept analytics cookies.</li>
            </ul>

            <h2>Camera and microphone</h2>
            <p>A practice interview can optionally use your camera and microphone. You are asked for permission by your browser and can decline; the interview still works without either.</p>
            <ul>
              <li><strong>Video is analysed in your browser and never uploaded.</strong> Eye contact, posture and engagement are measured on your device using Google&apos;s MediaPipe library, loaded from a public CDN. Only the resulting numbers (for example &ldquo;eye contact 72%&rdquo;) are sent to us. No video or images leave your device, and none are recorded.</li>
              <li><strong>Speech-to-text is performed by your browser, not by us.</strong> In Chrome and Edge this uses the browser&apos;s built-in speech recognition, which sends audio to Google for transcription under Google&apos;s privacy policy. We receive only the resulting text. If you prefer not to use it, type your answers instead — the microphone button is optional.</li>
            </ul>

            <h2>How we use it</h2>
            <p>We use your data to provide mock interviews, generate feedback, track progress, and improve Almaprep. For institution accounts, relevant data is made available to authorized staff at your institution.</p>

            <h2>AI providers</h2>
            <p>Questions and feedback are generated by third-party AI providers. Your answers, and your resume if you upload one, are sent to them to produce that feedback. We currently use Groq, OpenAI and Google (Gemini), and may change providers as the product develops.</p>
            <p>These providers process the text on our behalf as subprocessors. What each one is permitted to do with it is governed by our agreement with that provider; if you need the current list and their terms for a procurement or DPA review, email us and we will provide it.</p>

            <h2>Student data and institutions</h2>
            <p>When an institution deploys Almaprep, the institution is the owner of its students&apos; data and we act as a processor on its behalf. We do not sell student data.</p>

            <h2>Children&apos;s privacy</h2>
            <p>Almaprep is intended for use by students, including minors, primarily through their school or institution. For students under 13, we rely on the institution or a parent/guardian to provide the appropriate consent before an account is created, consistent with the principles of COPPA and applicable local law. We collect only the data needed to provide interview practice and feedback. If you believe a child has created an account without the required consent, contact us at <a href="mailto:privacy@almaprep.app">privacy@almaprep.app</a> and we will delete it.</p>

            <h2>Your choices</h2>
            <p>You can request access to or deletion of your personal data by contacting us. Institution users should also contact their administrator. You can also delete your account and its data yourself from your profile page, which removes your practice history, reports, badges and streaks, and the account itself.</p>
            <p>Analytics cookies are optional and are not set unless you accept them. Declining does not affect any part of the product.</p>

            <h2>Contact</h2>
            <p>Questions about privacy? Email <a href="mailto:privacy@almaprep.app">privacy@almaprep.app</a>.</p>
          </div>
        </section>
      </main>

      <Footer />
    </div>
  )
}
